// :composeApp — the Tanvrit Accounting Compose Multiplatform app.
//
// Targets: android / desktop(JVM) / iOS (arm64 + simulatorArm64, macOS hosts
// only) / wasmJs(browser). Modelled on platforms/ai's module setup: every
// version comes from gradle/libs.versions.toml and every Tanvrit dependency
// resolves from https://maven.tanvrit.com (no credentials).

import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.android.application)
    // ktlint is applied to every subproject from the root build.gradle.kts
    // (plugin catalog pin; engine pinned to 1.5.0 there).
}

// ─── Build identity ──────────────────────────────────────────────────────────
// The Settings "About" surface reads these generated constants rather than any
// hardcoded version literal, so the displayed version is always the truth.
// Everything the task captures is resolved eagerly at script level (plain
// Strings/File) so it stays configuration-cache safe.
val appVersionName = providers.gradleProperty("VERSION_NAME").getOrElse("1.0.0")
val appVersionCode = providers.gradleProperty("VERSION_CODE").map(String::toInt).getOrElse(1)
val sdkVersionForIdentity = providers.gradleProperty("TANVRIT_SDK_VERSION").getOrElse("unknown")
val buildIdentityOutDir = File(layout.buildDirectory.asFile.get(), "generated/identity")

val generateBuildIdentity =
    tasks.register("generateBuildIdentity") {
        // Configuration-cache safe: copy script-level values into task-locals
        // before doLast so the action captures plain Strings/File, not the
        // script object.
        val ver = appVersionName
        val code = appVersionCode
        val sdk = sdkVersionForIdentity
        val outDir = buildIdentityOutDir
        inputs.property("ver", ver)
        inputs.property("code", code)
        inputs.property("sdk", sdk)
        outputs.dir(outDir)
        doLast {
            val f = File(outDir, "com/tanvrit/accounting/BuildIdentity.kt")
            f.parentFile.mkdirs()
            f.writeText(
                "package com.tanvrit.accounting\n\n" +
                    "// GENERATED by :composeApp:generateBuildIdentity — do not edit.\n" +
                    "internal object BuildIdentity {\n" +
                    "    const val VERSION_NAME: String = \"$ver\"\n" +
                    "    const val VERSION_CODE: Int = $code\n" +
                    "    const val SDK_VERSION: String = \"$sdk\"\n" +
                    "}\n",
            )
        }
    }

// ─── Apple target gating ─────────────────────────────────────────────────────
// Kotlin/Native has no linux_aarch64/mingw host. Declaring the Apple targets
// only on a macOS host means every task graph (desktop, wasm, android, lint)
// still configures on CI machines that are not Macs; on macOS the target set
// is byte-for-byte what ships. Same approach as platforms/ai.
val isMacHost: Boolean = System.getProperty("os.name").startsWith("Mac", ignoreCase = true)

kotlin {
    // Intentional opt-in to stable expect/actual classes (KT-61573 warning).
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(JvmTarget.JVM_17)
                }
            }
        }
    }

    jvm("desktop")

    if (isMacHost) {
        listOf(
            iosArm64(),
            iosSimulatorArm64(),
        ).forEach { iosTarget ->
            iosTarget.binaries.framework {
                baseName = "ComposeApp"
                isStatic = true
            }
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            val rootDirPath = project.rootDir.path
            val projectDirPath = project.projectDir.path
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                devServer =
                    (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                        port = 3000
                        static(rootDirPath, true)
                        static(projectDirPath, true)
                    }
            }
        }
        binaries.executable()
    }

    sourceSets {
        all {
            // kotlin.time.Clock (kotlinx-datetime 0.8 + Kotlin 2.4.x).
            languageSettings.optIn("kotlin.time.ExperimentalTime")
        }

        commonMain {
            kotlin.srcDir(generateBuildIdentity)
        }

        commonMain.dependencies {
            // Compose — direct catalog coordinates (plugin accessors are
            // deprecated in CMP 1.12).
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.material.ripple)
            implementation(libs.compose.material.icons.core)
            // material-icons-core must be declared explicitly beside extended:
            // its commonMain klib (which defines the Icons object) is not
            // transitively forwarded onto the metadata classpath.
            implementation(libs.compose.material.icons.extended)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)

            implementation(libs.androidx.navigation.compose)
            implementation(libs.androidx.navigation.common)
            implementation(libs.androidx.navigation.runtime)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)

            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

            // Tanvrit core + accounting contracts (models, DTOs, Money,
            // AppViewModel, TanvritSDK bootstrap).
            implementation(libs.tanvrit.core)
            implementation(libs.tanvrit.core.accounting)

            // Tanvrit SDK foundation — storageModule (offline cache),
            // authModule (tokens), businessModule (active business), uiModule
            // (TanvritTheme / TanvritDesignSystem / Premium components).
            implementation(libs.tanvrit.storage)
            implementation(libs.tanvrit.auth)
            implementation(libs.tanvrit.business)
            implementation(libs.tanvrit.ui)

            // The accounting SDK module — Networks, offline-first
            // Repositories, ViewModels, AccountingModule (Koin).
            implementation(libs.tanvrit.accounting)
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }

        getByName("desktopMain").dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
        }

        getByName("desktopTest").dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.compose.ui.test)
        }

        androidMain.dependencies {
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.kotlinx.coroutines.android)
        }

        if (isMacHost) {
            iosMain.dependencies { }
        }

        getByName("wasmJsMain").dependencies {
            // Consumer apps must declare the wasm-js stdlib matching the
            // Kotlin the SDK klibs were built with — Compose otherwise pulls
            // an older stdlib ("Symbol for Any not found"). Tracks
            // libs.versions.kotlin.
            implementation(libs.kotlin.stdlib.wasm.js)

            // Web persistence (SDK storage → sql.js): declare the runtime
            // npm dep + the plugin our webpack.config.d/sqljs.js requires
            // (mirrors platforms/ai's proven wasmJsMain block).
            implementation(npm("sql.js", "1.8.0"))
            implementation(devNpm("copy-webpack-plugin", "9.1.0"))
        }
    }
}

android {
    namespace = "com.tanvrit.accounting"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.tanvrit.accounting"
        minSdk = 26
        // targetSdk tracks compileSdk (repo convention: they move together).
        targetSdk = 37
        versionCode = appVersionCode
        versionName = appVersionName
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    // Release signing is env-driven and never committed. With no keystore the
    // release AAB is unsigned (fine for scaffold/dry-run), matching the
    // convention in platforms/ai and platforms/wedding.
    signingConfigs {
        create("release") {
            val keystorePath = System.getenv("RELEASE_STORE_FILE")
            if (!keystorePath.isNullOrBlank() && file(keystorePath).exists()) {
                storeFile = file(keystorePath)
                storePassword = System.getenv("RELEASE_STORE_PASSWORD")
                keyAlias = System.getenv("RELEASE_KEY_ALIAS") ?: "tanvrit-accounting-release"
                keyPassword = System.getenv("RELEASE_KEY_PASSWORD")
            } else {
                logger.warn("No release keystore (RELEASE_STORE_FILE unset) — release builds will be unsigned")
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            val keystorePath = System.getenv("RELEASE_STORE_FILE")
            if (!keystorePath.isNullOrBlank() && file(keystorePath).exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.tanvrit.accounting.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Tanvrit Accounting"
            packageVersion = appVersionName
            description = "Tanvrit Accounting — double-entry bookkeeping, GST/TDS compliance, bank reconciliation"
            vendor = "Tanvrit Pvt. Ltd."
            copyright = "© 2026 Tanvrit Pvt. Ltd."

            // Minimal jlink module set: storage opens SQLite over JDBC
            // (java.sql), TanvritClient uses java.net.http, multiplatform
            // persistence touches java.util.prefs on JVM.
            modules(
                "java.sql",
                "java.naming",
                "java.net.http",
                "java.prefs",
                "jdk.crypto.ec",
                "jdk.unsupported",
                "jdk.management",
            )

            macOS {
                bundleID = "com.tanvrit.accounting"
                dmgPackageVersion = appVersionName
                appCategory = "public.app-category.finance"
            }

            windows {
                menuGroup = "Tanvrit Accounting"
                upgradeUuid = "7c2e95a1-3b4d-4e8f-9a2c-6f1d0e5b8a34"
            }

            linux {
                packageName = "tanvrit-accounting"
                debMaintainer = "contact@tanvrit.com"
                appCategory = "Office"
                menuGroup = "Office"
            }
        }

        jvmArgs(
            "-Xmx1536m",
            "-Dfile.encoding=UTF-8",
        )
    }
}

// The fat desktop JAR can exceed 65535 entries; enable zip64.
tasks.withType<Zip>().configureEach {
    isZip64 = true
}
